services:
  - type: web
    name: auction-platform-api
    runtime: node
    repo: https://github.com/ertyyui950-star/ventmaster-api
    branch: auction-backend-v3
    rootDir: Desktop/auction-platform/backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push --skip-generate && node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        value: "file:/tmp/prod.db"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
